Vagrant.configure("2") do |config|
    config.vm.box = "bento/centos-6.7"
    config.vm.synced_folder ".", "/home/vagrant/app", mount_options: ["dmode=775,fmode=664"]
    config.vm.network "forwarded_port", guest: 8000, host: 8000
    config.vm.provision :shell, :path => "bin/vagrant-setup.sh"
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
    end
end
