AnalysisPageServer: AnalysisPageSVG.cpp tinyxml2.cpp cor.cpp AnalysisPageSVG.h tinyxml2.h cor.h catch.c SearchReplace2.cpp SearchReplace2.h catch.h
	R CMD SHLIB AnalysisPageSVG.cpp tinyxml2.cpp cor.cpp catch.c SearchReplace2.cpp R_init_AnalysisPageServer.cpp -o AnalysisPageServer.so
clean:
	rm *.o *.so
